Name:           perl-ExtUtils-MakeMaker
Version:        6.98
Release:        1%{?dist}
Summary:        Create a module Makefile
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/ExtUtils-MakeMaker/
Source0:        http://www.cpan.org/modules/by-module/ExtUtils/ExtUtils-MakeMaker-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(ExtUtils::Manifest)
BuildRequires:  perl(File::Spec) >= 0.8
BuildRequires:  perl(Pod::Man)
Requires:       perl(File::Spec) >= 0.8
Requires:       perl(Pod::Man)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This utility is designed to write a Makefile for an extension module from a
Makefile.PL. It is based on the Makefile.SH model provided by Andy
Dougherty and the perl5-porters.

%prep
%setup -q -n ExtUtils-MakeMaker-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json NOTES PATCHING README README.packaging TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_bindir}/instmodsh
%{_mandir}/man1/instmodsh.1.gz
%exclude /usr/share/perl5/vendor_perl/CPAN/
%exclude %{_mandir}/man3/CPAN*
%exclude %{_mandir}/man3/version.3pm.gz
%exclude %{_mandir}/man3/version::Internals.3pm.gz

%changelog
* Mon Aug 07 2017 Ryan Fife <ryan@fife-v.com> 6.98-1
- Specfile autogenerated by cpanspec 1.78.
