Name:           perl-Encode
Version:        2.92
Release:        1%{?dist}
Summary:        Character encodings in Perl
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Encode/
Source0:        http://www.cpan.org/authors/id/D/DA/DANKOGAI/Encode-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(Exporter) >= 5.57
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(ExtUtils::Manifest)
BuildRequires:  perl(parent) >= 0.221
BuildRequires:  perl(Storable)
BuildRequires:  perl(Test::More) >= 0.81_01
Requires:       perl(Exporter) >= 5.57
Requires:       perl(parent) >= 0.221
Requires:       perl(Storable)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The Encode module provides the interface between Perl strings and the rest
of the system. Perl strings are sequences of characters.

%prep
%setup -q -n Encode-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc AUTHORS Changes META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Encode*
%{perl_vendorarch}/encoding.pm
%{_mandir}/man3/*
%{_mandir}/man1/enc2xs.1.gz
%{_mandir}/man1/encguess.1.gz
%{_mandir}/man1/piconv.1.gz
/usr/bin/enc2xs
/usr/bin/encguess
/usr/bin/piconv

%changelog
* Mon Aug 07 2017 Ryan Fife <ryan@fife-v.com> 2.92-1
- Specfile autogenerated by cpanspec 1.78.
