Name:           perl-JavaScript-Minifier-XS
Version:        0.09
Release:        1%{?dist}
Summary:        XS based JavaScript minifier
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/JavaScript-Minifier-XS/
Source0:        http://www.cpan.org/modules/by-module/JavaScript/JavaScript-Minifier-XS-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 1:v5.8.8
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
JavaScript::Minifier::XS is a JavaScript "minifier"; its designed to remove
un-necessary whitespace and comments from JavaScript files, which also not
breaking the JavaScript.

%prep
%setup -q -n JavaScript-Minifier-XS-%{version}

%build
%{__perl} Build.PL installdirs=vendor optimize="$RPM_OPT_FLAGS"
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/JavaScript*
%{_mandir}/man3/*

%changelog
* Mon Aug 07 2017 Ryan Fife <ryan@fife-v.com> 0.09-1
- Specfile autogenerated by cpanspec 1.78.
