Name:           perl-Business-Hours
Version:        0.12
Release:        1%{?dist}
Summary:        Calculate business hours in a time period
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Business-Hours/
Source0:        http://www.cpan.org/authors/id/R/RU/RUZ/Business-Hours-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(ExtUtils::Manifest)
BuildRequires:  perl(Set::IntSpan) >= 1.12
BuildRequires:  perl(Time::Local)
BuildRequires:  perl(Test::Simple)
Requires:       perl(Set::IntSpan) >= 1.12
Requires:       perl(Time::Local)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module is a simple tool for calculating business hours in a time
period. Over time, additional functionality will be added to make it easy
to calculate the number of business hours between arbitrary dates.

%prep
%setup -q -n Business-Hours-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Aug 04 2017 Ryan Fife <ryan.fife@fifeventures.co.uk> 0.12-1
- Specfile autogenerated by cpanspec 1.78.
[root@configuration hi]#
