Name:           perl-Date-Extract
Version:        0.06
Release:        1%{?dist}
Summary:        Date::Extract Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Date-Extract/
Source0:        http://www.cpan.org/authors/id/A/AL/ALEXMV/Date-Extract-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Carp)
BuildRequires:  perl(CPAN)
BuildRequires:  perl(Class::Data::Inheritable)
BuildRequires:  perl(DateTime::Format::Natural) >= 0.60
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(List::Util)
BuildRequires:  perl(parent)
BuildRequires:  perl(Test::MockTime)
BuildRequires:  perl(Test::More)
Requires:       perl(Carp)
Requires:       perl(Class::Data::Inheritable)
Requires:       perl(DateTime::Format::Natural) >= 0.60
Requires:       perl(List::Util)
Requires:       perl(parent)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
SYNOPSIS        my $parser = Date::Extract->new();        my $dt = $parser-
>extract($arbitrary_text)            or die "No date found.";
return $dt->ymd;

%prep
%setup -q -n Date-Extract-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Aug 04 2017 Ryan Fife <ryan@fife-v.com> 0.06-1
- Specfile autogenerated by cpanspec 1.78.
